### PR TITLE
bugfix Emacs TAGS format

### LINKED ISSUE #42: incorrect emacs tag format
in

https://github.com/elaforge/fast-tags/blob/master/src/FastTags/Emacs.hs#L40

```
, showt (linenum-1) <> "," <> showt linenum
```

but I think this is supposed to be the line and then the byte offset, c.f. https://stackoverflow.com/questions/1990579

In addition, the `Token.posPrefix pos` is more typically the entire line as it is shown in the preview mode.

### PR DESCRIPTION
**Pull request by fommil**
fixes #42

This more correctly matches the output that I see from something like `exuberant-ctags`, i.e. https://stackoverflow.com/questions/1990579

### CODE REVIEW

File: src/FastTags/LexerTypes.hs [hunk 1]
```diff
@@ -77,8 +78,13 @@ mkAlexInput s trackPrefixes = AlexInput
...
 
 mkSrcPos :: FilePath -> AlexInput -> SrcPos
-mkSrcPos filename (AlexInput {aiLine, aiPrefix}) =
-    SrcPos { posFile = filename, posLine = aiLine, posPrefix = aiPrefix }
+mkSrcPos filename (AlexInput {aiLine, aiPrefix, aiAbsPos}) =
+    SrcPos { posFile = filename
+           , posLine = aiLine
+           , posOffset = Offset aiAbsPos
+           , posPrefix = aiPrefix
+           , posText = aiPrefix <> (fromString $ show $ unLine aiLine)
```
Comment (fommil) [inline src/FastTags/LexerTypes.hs]: this is just a placeholder...

Comment (fommil) [reply src/FastTags/LexerTypes.hs]: we have the `aiInput` and the location of the match, so it should be a case of taking that position to the next newline.

**Comment by fommil** [comment]
It is late, I will fix the tests in the morning... but I have confirmed that this fixes the problem :smile:

I suspect there is a similar bug in `hasktags` as I seen the same behaviour there also.

File: src/FastTags/LexerTypes.hs [hunk 2]
```diff
@@ -77,8 +77,13 @@ mkAlexInput s trackPrefixes = AlexInput
...
 
 mkSrcPos :: FilePath -> AlexInput -> SrcPos
-mkSrcPos filename (AlexInput {aiLine, aiPrefix}) =
-    SrcPos { posFile = filename, posLine = aiLine, posPrefix = aiPrefix }
+mkSrcPos filename (AlexInput {aiInput, aiLine, aiPrefix, aiAbsPos}) =
+    SrcPos { posFile = filename
+           , posLine = aiLine
+           , posOffset = Offset aiAbsPos
+           , posPrefix = aiPrefix
+           , posText = aiPrefix <> (Text.takeWhile (/= '\n') aiInput)
```
Comment (sergv) [inline src/FastTags/LexerTypes.hs]: I think it would be nice to not populate this field if `aiTrackPrefixes` is `False`. I.e. when we're generating tags for vim - there's no reason to keep lots of lines around which will not be consumed in the end.

**Comment by fommil** [comment]
@sergv @elaforge  I have updated the PR so the tests now pass.

I can also confirm that `exuberant-ctags` generates this sort of thing

```
data RealWorld a whereRealWorld103,2929
```

the current release of `fast-tags` generates

```
data RealWorldRealWorld102,103
```

(note that there is only a prefix, confusing Emacs, the line is off by one, and the final column is wrong)

this patch now produces

```
data RealWorld a whereRealWorld103,2943
```

I am unsure what is causing the 2929 vs 2943 mismatch, it looks to be that `ctags` uses the offset of the start of the line whereas this produces the offset for the match... I think we may actually be doing better than `exuberant-ctags` in that case

File: src/FastTags/Token.hs [hunk 3]
```diff
@@ -21,22 +21,27 @@ instance Show a => Show (Pos a) where
...
 increaseLine :: Line -> Line
 increaseLine (Line n) = Line $! n + 1
 
 data SrcPos = SrcPos {
     posFile     :: !FilePath
     , posLine   :: {-# UNPACK #-} !Line
+    , posOffset :: {-# UNPACK #-} !Offset
     -- | No need to keep prefix strict since most of the prefixes will not be
     -- used.
     , posPrefix :: Text
```
[the remark this answers is not in the document]
Comment (fommil) [reply src/FastTags/Token.hs]: all these fields are now used.

**Comment by fommil** [comment]
looks like the offset is supposed to be the start of the line, https://en.wikipedia.org/wiki/Ctags#Etags_2 I'll make a small change for that.

**Comment by elaforge** [comment]
Looks good to me, merging.

Thanks for giving emacs some attention, it needed it!

**Comment by elaforge** [comment]
BTW I'll do a cabal release soon unless you have some other change in mind.
